amp: false
batch_size: 5000
bert: ashabrawy/egy_aligned_msa
bert_pad_index: null
bert_pooling: mean
binarize: false
bos_index: 2
buckets: 32
build: false
cache: false
char_pad_index: null
checkpoint: false
clip: 5.0
dev: ./data/Egyptian/arz_dev.conllx
device: '0'
dist: ddp
embed: glove-6b-100
encoder: bert
encoder_dropout: 0.1
epochs: 10
eps: 1.0e-08
even: false
feat: null
fix_len: 20
local_rank: 0
lr: 5.0e-05
lr_rate: 10
max_len: null
min_freq: 2
mix_dropout: 0.0
mlp_dropout: 0.33
mode: train
mu: 0.9
n_arc_mlp: 500
n_bert_layers: 4
n_chars: null
n_rel_mlp: 100
n_rels: 9
n_tags: null
n_words: 30000
nu: 0.999
pad_index: 0
partial: false
path: models/aligned_egy.model
patience: 100
proj: true
punct: false
seed: 1
steps: 2262
test: ./data/Egyptian/arz_test.conllx
threads: 16
train: ./data/patb-egy_train.conllx
tree: true
unk_index: 1
update_steps: 4
verbose: true
wandb: false
warmup: 0.1
weight_decay: 0
workers: 0
